import type { DocsNavigationConfig } from '@kushagradhawan/kookie-blocks';
import {
  Download01Icon,
  Settings01Icon,
  ColorsIcon,
  Grid02Icon,
  Layers01Icon,
  SwatchIcon,
  JoinRoundIcon,
  TextSquareIcon,
  LayoutIcon,
  InputCursorTextIcon,
  LayoutTopIcon,
  DropdownFieldTypeIcon,
  Image01Icon,
  Asterisk02Icon,
  UserCircleIcon,
  Tag01Icon,
  Alert02Icon,
  SquareIcon,
  Heading01Icon,
  TextIcon,
  MessageEdit01Icon,
  LeftToRightListBulletIcon,
} from '@hugeicons/core-free-icons';

export const docsNavigation: DocsNavigationConfig = {
  groups: [
    {
      label: 'Get Started',
      items: [{ href: '/docs/installation', title: 'Installation', icon: Download01Icon }],
    },
    {
      label: 'Theme',
      items: [
        { href: '/docs/theme', title: 'Theme', icon: Settings01Icon },
        { href: '/docs/colors', title: 'Colors', icon: ColorsIcon },
        { href: '/docs/constants', title: 'Constants', icon: Grid02Icon, badge: { content: 'Alpha', size: '1', highContrast: true } },
        { href: '/docs/shadows', title: 'Shadows', icon: Layers01Icon },
        { href: '/docs/material', title: 'Material', icon: SwatchIcon, badge: { content: 'Alpha', size: '1', highContrast: true } },
        { href: '/docs/radius', title: 'Radius', icon: JoinRoundIcon },
        { href: '/docs/typography', title: 'Typography', icon: TextSquareIcon },
      ],
    },
    {
      label: 'Components',
      items: [
        {
          href: '/docs/avatar',
          title: 'Avatar',
          icon: UserCircleIcon,
          badge: { content: 'Development', color: 'gray', size: '1', highContrast: true },
        },
        {
          href: '/docs/badge',
          title: 'Badge',
          icon: Tag01Icon,
          badge: { content: 'Development', color: 'gray', size: '1', highContrast: true },
        },
        {
          href: '/docs/button',
          title: 'Button',
          icon: Asterisk02Icon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/callout',
          title: 'Callout',
          icon: Alert02Icon,
          badge: { content: 'Development', color: 'gray', size: '1', highContrast: true },
        },
        {
          href: '/docs/card',
          title: 'Card',
          icon: SquareIcon,
          badge: { content: 'Development', color: 'gray', size: '1', highContrast: true },
        },
        {
          href: '/docs/chatbar',
          title: 'Chatbar',
          icon: MessageEdit01Icon,
          badge: { content: 'Development', color: 'gray', size: '1', highContrast: true },
        },
        {
          href: '/docs/combobox',
          title: 'Combobox',
          icon: DropdownFieldTypeIcon,
          badge: { content: 'Development', color: 'gray', size: '1', highContrast: true },
        },
        {
          href: '/docs/heading',
          title: 'Heading',
          icon: Heading01Icon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/icon-button',
          title: 'Icon Button',
          icon: Asterisk02Icon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/image',
          title: 'Image',
          icon: Image01Icon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/navbar',
          title: 'Navbar',
          icon: LayoutTopIcon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/segmented-control',
          title: 'Segmented Control',
          icon: Asterisk02Icon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/shell',
          title: 'Shell',
          icon: LayoutIcon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/sidebar',
          title: 'Sidebar (Presentation)',
          icon: LeftToRightListBulletIcon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/text',
          title: 'Text',
          icon: TextIcon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/text-field',
          title: 'Text Field',
          icon: InputCursorTextIcon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/toggle-button',
          title: 'Toggle Button',
          icon: Asterisk02Icon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
        {
          href: '/docs/toggle-icon-button',
          title: 'Toggle Icon Button',
          icon: Asterisk02Icon,
          badge: { content: 'Alpha', size: '1', highContrast: true },
        },
      ],
    },
  ],
};
