export * from './color.prop.js';
export * from './high-contrast.prop.js';
export * from './layout.props.js';
export * from './leading-trim.prop.js';
export * from './margin.props.js';
export * from './prop-def.js';
export * from './radius.prop.js';
export * from './text-align.prop.js';
export * from './weight.prop.js';
